name: smartplants
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.11
  syncfusion_flutter_gauges: ^25.1.35
  go_router: ^13.2.2
  sleek_circular_slider: ^2.0.1
  http: ^1.2.1
  dio: ^5.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2


flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icon/logo.png"
  android: true
  android_12:
    color: "#FFFFFF"
    image: "assets/icon/logo.png"
    icon_background_color: "#FFFFFF"


flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/logo.png"

  flutter_lints: ^3.0.2

flutter:
  assets:
    - assets/icon/
    - assets/image/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Thin.ttf
          weight: 200
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Poppins-Black.ttf
          weight: 900

  uses-material-design: true